name: flujo-ci-basico

on: [push]

jobs:
  test-node:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout del repositorio
        uses: actions/checkout@v4
    
      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
    
      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar test
        run: npm test
