name: flujo-ci-basico

on: [push]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout del repositorio
        uses: actions/checkout@v4
    
      - name: Obtener IP pública
        id: ip
        uses: haythem/public-ip@v1.3
    
      - name: Imprimir mensaje
        run: echo "¡Hola mundo desde ${{ steps.ip.outputs.ipv4 }}!"
